/**
 * Trip Model
 * 
 * Stores saved travel itineraries generated by the AI.
 * Includes the full structured itinerary with budget breakdown.
 */

const mongoose = require('mongoose');

const tripSchema = new mongoose.Schema(
  {
    // Trip destination (city/country)
    destination: {
      type: String,
      required: true,
    },
    // Number of days for the trip
    days: {
      type: Number,
      required: true,
    },
    // Total budget in USD
    budget: {
      type: Number,
      required: true,
    },
    // User's interests/preferences
    interests: {
      type: [String],
      default: [],
    },
    // The generated itinerary (structured JSON)
    itinerary: {
      type: mongoose.Schema.Types.Mixed,
      required: true,
    },
    // Budget breakdown — stored as Mixed to preserve full nested structure
    // (total, days, perDay, tier, breakdown: {hotel, food, ...}, perDayBreakdown: {...})
    budgetBreakdown: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
    // Additional generated content
    travelTips: [String],
    packingList: [String],
    localFood: [String],
    lessCrowdedPlaces: [String],
    weatherInfo: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Trip', tripSchema);
